### PR TITLE
Overwrite global permissions for course members during object creation

### LINKED ISSUE #457: Permission "Download" is not deactivated for CourseMembers when creating a new series
**Describe the bug**
Permission "Download" **is not deactivated** for course members when manually creating a new series, if the permission "Download" is set in the global CourseMember role template of the ilias installation. 

**To Reproduce**
1. Activate permission "Download Videos" in the global role template for CourseMembers
2. Create a new ILIAS Course
3. Create a new OpencastSeries, by deactivating the permission "Download" under "Rights for members"
4. Click on "Save" and go to the permissions tab of the newly created Series
5. --> Bug: Permission "Download" is activated

**Expected behavior**
Deactivating the checkbox "Download" when manually creating a OpencastSeries should always result in a deactivated "Download" permission in the newly created series, regardless of what is configured in the global role template."

**Screenshots**

Settings before manually creating  a OpencastSeries
Image

**Environment (please complete the following information):**
    ILIAS version: v9.12 2025-07-15
    Plugin version: 9.2.3
    Opencast version: 17
    Browser: Firefox

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #457 

It enforces overwriting of global permissions for course members during object creation.

* Ensures that course member permissions take precedence over global role templates when creating objects manually.
* Improves default permission handling to better prevent unwanted permission inheritance.

### CODE REVIEW

**Comment by ferishili** [comment]
The ReviewApp for this PR:

http://oc-pr-458.opencast.k8s.sr.solutions/

**Comment by dagraf** [comment]
My tests where successfull. Thx for the fix! 

@chfsx: Can you please review this PR and merge it, if everything is fine or comment it? Thx!

**Comment by dagraf** [comment]
@chfsx: Reminder.

File: classes/class.ilObjOpenCastAccess.php [hunk 1]
```diff
@@ -575,6 +578,18 @@ private static function setDefaultPerms(int $ref_id, int $role_id, array $perms_
...
+        // In case we are forced to prevent some perms.
+        if (!empty($perms_to_prevent)) {
+            foreach ($perms_to_prevent as $prevented_perm) {
+                $prefix = in_array($prevented_perm, self::$custom_rights) ? "rep_robj_xoct_perm_" : "";
+                $perm_name = $prefix . $prevented_perm;
+                $prevented_ops_id = $DIC->rbac()->review()->_getOperationIdByName($perm_name);
+                $key_to_remove = array_search($prevented_ops_id, $ops_ids, true);
+                if ($key_to_remove !== false) {
+                    unset($ops_ids[$key_to_remove]);
+                }
```
Comment (chfsx) [inline classes/class.ilObjOpenCastAccess.php:590]: I'm not an expert in RBAC and operations, but from my point of view, it looks good, but I can't guarantee it with 100% certainty. I think we should do it this way, and many thanks to @ferishili  for investigating.

**Review by chfsx — APPROVED** [review]

**Comment by dagraf** [comment]
@chfsx: How to proceed with this issue?

**Comment by chfsx** [comment]
I've merged this now in v9.3.0
